title: zhen735的个人主页
description: 学习笔记、论文阅读与项目记录
lang: zh-CN

url: "https://zhen735.github.io"
baseurl: ""
cover_image: /assets/images/cover.jpeg
cover_bg_color: "#28494d"
cover_color: "#ffffff"

author:
  name: zhen735
  url: https://github.com/zhen735

markdown: kramdown

collections:
  learning:
    output: true
    permalink: /learning/:name/

  papers:
    output: true
    permalink: /papers/:name/

  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: learning
    values:
      layout: default

  - scope:
      path: ""
      type: papers
    values:
      layout: default

  - scope:
      path: ""
      type: projects
    values:
      layout: default
